version: "3.8"
services:
    
    application:
        build: .
        image: application
        command: >
            sh -c "python manage.py makemigrations --noinput &&
                   python manage.py migrate --noinput &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
            - application_media:/app/media
            - application_static:/app/static
        environment:
            DJANGO_SETTINGS_MODULE: base.settings.dev
            PYTHONUNBUFFERED: 1
        env_file:
            - ./.env.docker
        ports: 
            - '8000:8000'
            - '3000:3000'
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        volumes:
            - db_data:/var/lib/postgresql/data/
        ports: 
            - '5434:5432'
        environment:
            POSTGRES_DB: application_db
            POSTGRES_USER: application_admin
            POSTGRES_PASSWORD: application_password

volumes:
    application_media:
    application_static:
    db_data: